name: EasyBedwars
main: net.nocpiun.bedwars.Main
author: NriotHrreion
version: 0.0.1
api-version: 1.13
commands:
   bedwars:
      usage: /bedwars <args>
      description: Bedwars Command
   hub:
      usage: /hub
      description: Teleport to the waiting hub
permissions:
   bedwars.admin:
      description: Let admin can manage the whole bedwars game
      default: op
